// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdyfekpeoeyymuqzujrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkeWZla3Blb2V5eW11cXp1anJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDI2NTQsImV4cCI6MjA2NjcxODY1NH0.tgYDr1pw4nKoqjOWEiKT35I6qT3O6DEFC66R2aS1bvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);