import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Send, Loader2, Sparkles } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { generateStudentDeliverable, StretchingPlanItem, StudentRecommendation } from '@/utils/studentReportGenerator';

interface Props {
  studentId: string;
  studentName?: string;
  analysisRunId?: string;
  // Passe o aiReport completo para geração automática (recomendado).
  aiReport?: any;
  failSafes?: any;
  nmAlerts?: any[];
  // Fallback manual (uso legado / edição fina antes de publicar)
  initialReportHtml?: string;
  initialRecommendations?: any[];
}

export const PublishToStudent = ({
  studentId,
  studentName = 'Aluno',
  analysisRunId,
  aiReport,
  failSafes,
  nmAlerts,
  initialReportHtml = '',
  initialRecommendations = [],
}: Props) => {
  const [open, setOpen] = useState(false);
  const [html, setHtml] = useState(initialReportHtml);
  const [recsList, setRecsList] = useState<StudentRecommendation[]>([]);
  const [stretchingPlan, setStretchingPlan] = useState<StretchingPlanItem[]>([]);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [loading, setLoading] = useState(false);

  // Gera automaticamente a entrega (relatório + recomendações + plano) a partir do aiReport
  useEffect(() => {
    if (aiReport) {
      const deliverable = generateStudentDeliverable({ studentName, aiReport, failSafes, nmAlerts });
      setHtml(deliverable.report_html);
      setRecsList(deliverable.recommendations);
      setStretchingPlan(deliverable.stretching_plan);
      setAutoGenerated(true);
    } else if (initialRecommendations.length > 0) {
      setRecsList(initialRecommendations.map((r: any) => ({
        category: r.category || 'geral',
        text: typeof r === 'string' ? r : r.text || r.message || '',
        is_alert: false,
      })));
    }
  }, [aiReport, studentName, failSafes, nmAlerts]);

  const recsText = recsList.map(r => r.text).join('\n');
  const setRecsFromText = (text: string) => {
    setRecsList(text.split('\n').filter(Boolean).map(t => ({ category: 'geral', text: t, is_alert: false })));
  };

  const publish = async () => {
    setLoading(true);
    try {
      // Desativa publicações antigas
      await supabase.from('ppa_plan_links').update({ active: false }).eq('student_id', studentId).eq('active', true);
      // Cria nova publicação com relatório, recomendações E plano estruturado de alongamento
      const { error } = await supabase.from('ppa_plan_links').insert({
        student_id: studentId,
        analysis_run_id: analysisRunId,
        active: true,
        published_at: new Date().toISOString(),
        report_html: html,
        recommendations: recsList,
        stretching_plan: stretchingPlan,
      } as any);
      if (error) throw error;
      toast.success('Relatório, recomendações e plano de alongamento publicados para o aluno');
      setOpen(false);
    } catch (e: any) { toast.error(e.message); } finally { setLoading(false); }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button><Send className="h-4 w-4 mr-2" /> Publicar para o Aluno</Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            Publicar entrega
            {autoGenerated && <Badge className="bg-green-100 text-green-700"><Sparkles className="h-3 w-3 mr-1" />Gerado automaticamente</Badge>}
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          {autoGenerated && (
            <p className="text-xs text-muted-foreground bg-muted p-2 rounded">
              O relatório, as recomendações e o plano de alongamento abaixo foram gerados automaticamente a partir da análise da IA.
              Você pode revisar e ajustar antes de publicar.
            </p>
          )}
          <div>
            <Label>Relatório (HTML)</Label>
            <Textarea rows={8} value={html} onChange={e => setHtml(e.target.value)} placeholder="<h2>Diagnóstico</h2><p>...</p>" />
          </div>
          <div>
            <Label>Recomendações (1 por linha)</Label>
            <Textarea rows={5} value={recsText} onChange={e => setRecsFromText(e.target.value)} placeholder="Trocar tênis de corrida por solado rígido nos treinos de carga.&#10;Evitar permanecer sentado mais de 60min." />
          </div>
          <div>
            <Label>Plano de Alongamento ({stretchingPlan.length} exercícios)</Label>
            <div className="border rounded-lg p-3 max-h-48 overflow-y-auto space-y-2 bg-muted/30">
              {stretchingPlan.length === 0 && <p className="text-xs text-muted-foreground">Nenhum exercício gerado ainda. Rode a análise com Gemini primeiro.</p>}
              {stretchingPlan.map(item => (
                <div key={item.order} className="text-sm flex items-center justify-between border-b last:border-0 pb-1">
                  <span>{item.order}. {item.name}</span>
                  <Badge variant="outline" className="text-xs">{item.sets}x {item.reps_or_time}</Badge>
                </div>
              ))}
            </div>
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => setOpen(false)}>Cancelar</Button>
          <Button onClick={publish} disabled={loading}>
            {loading ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Send className="h-4 w-4 mr-2" />}
            Publicar
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default PublishToStudent;
